<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-09-01T16:11:40 MDT" name="Default suite" finished-at="2020-09-01T16:11:40 MDT" duration-ms="87">
    <groups>
    </groups>
    <test started-at="2020-09-01T16:11:40 MDT" name="Default test" finished-at="2020-09-01T16:11:40 MDT" duration-ms="87">
      <class name="com.example.project.TestNgTest">
        <test-method signature="doLogin()[pri:1, instance:com.example.project.TestNgTest@34f7cfd9]" started-at="2020-09-01T16:11:40 MDT" name="doLogin" finished-at="2020-09-01T16:11:40 MDT" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method signature="doPasswordChange()[pri:2, instance:com.example.project.TestNgTest@34f7cfd9]" started-at="2020-09-01T16:11:40 MDT" name="doPasswordChange" finished-at="2020-09-01T16:11:40 MDT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doPasswordChange -->
        <test-method signature="doLogout()[pri:3, instance:com.example.project.TestNgTest@34f7cfd9]" started-at="2020-09-01T16:11:40 MDT" name="doLogout" finished-at="2020-09-01T16:11:40 MDT" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogout -->
        <test-method signature="valueMatch()[pri:4, instance:com.example.project.TestNgTest@34f7cfd9]" started-at="2020-09-01T16:11:40 MDT" name="valueMatch" finished-at="2020-09-01T16:11:40 MDT" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- valueMatch -->
        <test-method signature="negativeTestCase()[pri:5, instance:com.example.project.TestNgTest@34f7cfd9]" started-at="2020-09-01T16:11:40 MDT" name="negativeTestCase" finished-at="2020-09-01T16:11:40 MDT" duration-ms="3" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The item is lesser than expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The item is lesser than expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.example.project.TestNgTest.negativeTestCase(TestNgTest.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeTestCase -->
      </class> <!-- com.example.project.TestNgTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
